---
title: "Mid-semester changes"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
---

Please let me know if something changes in your schedule that make it difficult for you to attend the synchronous discussion. For example, if you or a family member gets sick.  If you believe that I have missed something important with these modifications please let me know. 

# Policy changes
* Office hours are held virtually over [Zoom](https://csuchico.zoom.us/my/rdonatello), and have been updated as follows: 
    - MW 2-3pm
    - Wed 10-12
    - Thu 12:30-1:20
* The SET's will be delivered online. This is not my choice. 
    - I trust that after our last module on missing data you are aware of the bias that can occur from non-response
    - I would ask that you be honest, but kind in your reviews for all your instructors. This is not easy on any of us right now and we're all doing our best. 
* Zoom Attendance
  - Friday class sessions will be recorded and uploaded to our Google Drive. 
  - If you have dogs, kids, family members etc at home and they want to 'join' you for class, it's fine! My dogs are gonna bark in my lecture videos, i'm not going to edit it out. It's life, and we need to give each other grace in this time. I don't care if you attend class in your PJ's with unbrushed hair. I don't even care if you are all sweaty b/c you just got back from a run or work out (while keeping a social distance), not like we'll smell ya! We each have a life outside of the classroom, and well this semester our life is going to become part of our classroom. It's okay, we'll roll with it. I'd rather see your lovely faces each week and know that you're still healthy, and willing to learn. 


# Grading changes

* The requirement to contribute to the ASCN, and to attend an external talk has been shifted to extra credit. 
    - Right now there are SO many opportunities to attend talks virtually about the statistics and epidemiology about this disease. 
* The 'slack participation' assignment has been removed. 
* The 4 learning journal check in's have been reduced to 2 (the ones we've already done). 
* The number of peer reviews has been reduced from 2 to 1.
    - But you have to provide 5 comments/corrections minimum, same 4 pts for the review. 
    - Spend more quality time on this, as the act of helping others is very important for your own learning. 
* The requirement to go to community coding & office hours has been modified to one check-in per topic. 
    - This was 8 pts, 2 pts per visit. If you attended CC/OH prior to break that will count as extra. 
    - This is our 1:1 time to make sure you're getting the information and help you need to learn. 
    - Preferrably this is during office hours, but if you are having difficulty that week you can use [this booking tool](https://dr-donatello.youcanbook.me) to find a time that works for us both. 
    - If these times don't work, PM me in Slack to discuss alternatives. 
* There will be no final exam. 
    - Each group will schedule a presentation time sometime during finals week. 
* Topic quizzes point value has been doubled. 
    - I'll need to think on how to accomodate for the earlier policy of dropping the lowest quiz score. It will probably be only out of the first 3, since you had a midterm on that material. 

# Procedural changes

We have 3 more topics left, each is schedule to take 2 weeks. Each topic consists of 5 graded items: A pre-topic QFT, a written assignment, peer review of the written assignment, asynchronous discussion in Slack, and a quiz. 

These are explained in detail below. Dates are noted as [Day][Week]. So Sun1 is sunday of week 1 of that topic. Wed2 is wednesday of the second week of that topic. You can always see the actual dates on the [class calendar](https://norcalbiostat.github.io/MATH456/schedule.html). 

* Pre-topic warmup (Sun1)
  - Join the Slack discussion channel for that topic. 
  - Go through the Question Formulation Technique exercise for the upcoming topic. 
    - The slides with modified instructions can be found in the topic folder in Google Drive. 
    - I will be checking this off on Monday morning (Mon1)
    
* Week 1 topic "content delivery" via mini lecture videos. 
  - I will create multiple variable length lectures that will follow the ASCN course notes and the textbook. 
  - These videos will be uploaded to our Google Drive. 
  - They will not replace reading the textbook. 
      
* Week 1 Synchronous class time (Fri1)
  - Housekeeping/catch up/check in
  - Group QFT report out.  
  - Other activities and/or discussion. 
    
* Week 1 Asynchronous work
  - Start the topic homework assignment.
  - Ask at least one question in the topic channel in Slack (Sat1)
          
* Week 2 topic "content delivery" via mini lecture videos. 

* Week 2 Asynchronous work          
  - Answer, or write comments on 2 other questions or posts in Slack (Tue2)
  - Homework assignment: draft due (Tue2), Peer review due (Thu2), Final due (Sat2)
  - Individual quiz (Thu 2)

* Week 2 Synchronous class time (Fri2)
  - Housekeeping/catch up/check in
  - Group quiz
  - Other activities and/or discussion. 
    
Once per topic you need to schedule a time to meet with me 1:1 to discuss your learning. See top of this page for more info. 

> Just FYI - I have no contingency plan in place for in case I get sick. 

  