---
title: "Frequently Asked Questions"
date: "Last Updated `r Sys.time()`"
output: html_document
---

# Where can I get help using R outside of class time? 

### Online
* Chico [R User Group](https://groups.google.com/forum/#!forum/chico-rug) Google email list and discussion board. 
    - Contribute your own solutions and advice as you can. 
* Stack Overflow using the `R` tag https://stackoverflow.com/questions/tagged/r 
    - Both of these are most helpful when you prepare a [minimal working example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) of your problem for the other users. 
* UCLA IDRE https://stats.idre.ucla.edu/r/ 
* Cookbook for R http://www.cookbook-r.com/
* R Examples repository http://dwoll.de/rexrepos/index.html 


### In Person: 

* [**Math Learning Lab**](http://www.csuchico.edu/math/Tutoring.shtml)
    - MLIB 4th floor
    - Mariby Cruz, Mitch Borgert, Jerry Tucay 

* **Community Coding Sessions** - TR 2-4pm MLIB 442

> _Come code with us! Bring your Data Science and coding questions, data, and projects. We aim to provide a helpful and friendly working environment where you can work, ask questions or discuss ideas related to R, Python, Data Science, or more generally data visualization and analysis._

* **Robin Donatello** - Stat professor. Holt 202. rdonatello@csuchico.edu 
    - MW 11-12 pm. Holt 155. 
    - Most community coding sessions. 
* **Edward Roualdes** - Stat professor. Holt 204. eroualdes@csuchico.edu
    - TR 1-2pm
    - Community Coding T 2-4 and R 3-4. 
* **Eduardo Gomez** - peer mentor. egomez42@mail.csuchico.edu
* **Ricardo Aguilar** - peer mentor. raguilar11@mail.csuchico.edu

