---
title: "Learning Tools"
output: 
  html_document: 
    toc: yes
    toc_float: true
---

## Learning Journals (LJ)

A Google doc where you will be writing responses and reflections to certain in-class activities. [Why use a learning Journal?](https://www.teachthought.com/literacy/20-types-of-learning-journals-that-help-students-think/)

* Date each entry. Write entries in reverse chronological order, from newest at the top to oldest at the bottom. 
* Use 1st level headers for each date so a nice outline is created that helps both of us navigate
* The Canvas assignment in will contain a running list of LJ entries to date, and will be updated every few weeks before check-ins. 



## [Question Formulation](https://www.teachthought.com/project-based-learning/qft/) (QFT)
The backbone of the scientific process is asking and trying to answer questions. The QFT activity will help learners learn how to brainstorm and ask questions freely, how to work with open and close ended questions, and what they can learn from asking questions. 

:::{.callout-tip icon=true}
This approach encourages students to respond with "Yes, and..." to the thoughts of others _without judging or working to answer these questions_. 
:::


**General process**: 

1. You will be presented with a Question Focus / prompt. 
2. In a group you will produce questions about the focus topic using some guiding rules. 
    a. Ask as many questions as you can
    b. Do not stop to answer, judge or to discuss the questions
    c. Write down every question exactly as it is stated
    d. Change any statement into a question
3. Identify closed and open ended questions, practice converting between the two. 
4. Prioritize questions. Which are the ones you consider most important? 
5. In a shared Google slides file (copy the last slide for your team): 
    - Share questions converted from open to closed, and closed to open format. 
    - Your top 3 questions, with rational for their ranking. 
6. (After class) Reflect on the activity in your Learning Journal. 
    - What did you learn? 
    - How can you use what you learned? 
    - How are your team's questions and priorities similar/different than other teams? 
    

## Think-Pair-Share (TPS)

These are short periods (1-2 minutes) of writing in your Learning Journal that may be shared with a neighbor or the class. 


## Peer Review (PR)

Most assignments will have a Draft due date. Then a period of peer review for approx 2 days, where your job is to help your classmate get the best score possible. This includes helping spot check their code, identifying places that can be removed or fixed, or guidance on how to work out a problem. After the peer review window has closed, you have another 1-2 days to make corrections and submit your final version. 

### Why do we do peer review?

* Everyone has different thought processes and may have approached the question from a different perspective that can help you learn the material.
* Co-authoring and reviewing your peers work is part of a professional research position.
* Learning how to provide good feedback will make you a better collaborator
* This is a delayed version of paired programming - another set of eyeballs can typically help you find your mistake.
* I will be looking for different things than your peers will be. This is a good thing. They are looking from “untrained eyes”, which can be very critical to make sure you are explaining yourself clearly. I can better “figure out” what you are meaning to say - they are the ones that will best tell you when/where you need to explain your findings better.
    
No matter what you end up doing after graduation, the quality of your ideas and work will be judged, in a large measure, by how well you can communicate in writing to diverse audiences. Participating in peer review can help you learn to shape their written language as a medium of communication with readers. [[Ref.]](https://teachingcenter.wustl.edu/resources/writing-assignments-feedback/using-peer-review-to-help-students-improve-their-writing/)


### How do I review my peers work?

* Check the [Peer Review Rotation](https://docs.google.com/spreadsheets/d/1M8Tbszv23U5Uqxiu3kYbmE_WZNmmZj9gyRRa70MMryM) spreadsheet in Google Drive to see who you are scheduled to review.
* If one of your reviewees did not submit the assignment DM them in Discord first to see if they are just running a little late. 
    - If it’s getting reasonably late then just pick another person to review that doesn’t have a lot of comments so far and DM me to let me know.
* By using comment bubbles, provide feedback to your peers.
* Be specific. Give the type of feedback that you want to receive.
* Minimum four corrections or suggestions for improvement.
    
### Giving good feedback

* Compliment the author. What did you like about their writing or plots?
* Make specific suggestions regarding things like word choices, use of details, organization, topic
* Mark corrections such as spelling, grammar, punctuation, analysis methods, coding errors, but don’t try to turn their paper or style into your style.
* If you find a claim that is not supported by data in the document (or cited) be sure to point it out.
* Check their work against what is required. Do they have all required elements?

### Grading of peer reviews

As I do my reviews on the same document, I will be reading and assessing your peer review. If I find your review is not providing quality feedback to the author you will not receive credit for that review. You may see the cells in the peer review spreadsheet changing color as I check off your review.


:::{.callout-important}
If you consistently do not turn in a draft that is complete enough for a review, or consistently provide sub-par reviews to your classmates, I reserve the right to stop assigning you work to review and stop having your work reviewed. You will not have the ability to make up these points. 
:::


## Quizzes (Qz)
Quizzes are a great way to test yourself, enhance recall, and self-assess your comprehension of the subject. Questions come from the textbook, Applied Stats Course Notes, and in-class discussion. Quizzes are administered in Google Forms, and done in two parts. Expect 10-20 questions each time. 

1. **Individual**: First try to answer as many questions without looking at your notes. Then use your notes to answer the rest. 

2. **Group**: After the individual quiz closes I will choose 1-4 questions that scored the lowest. We will do a class-wide discussion of those topics, then you will work in groups to redo the selected questions for half credit. 


## Exam Error Assessment

For the midterm you will have an opportunity assess your errors on the midterm, make corrections, review the corrections with me, for a partial return of the credit lost. [Error Assessment Form](notes/Analyzing exam errors.pdf)

* Download the error assessment form. 
* Review page 3, six types of test taking errors. 
* Fill out page 2 by using the commenting/editing tool in Adobe to add text.
* Redo the problems you got wrong on a separate form. 
* Make an appt with me to go over your corrected answers. **You must have your error assessment form filled out before you meet with me.**


<!---

## 3-2-1 Bridge (Bridge)
This activity is designed for you to visualize and reflect on how your thinking and perceptions on a specific topic change throughout a module, or course. 

https://norcalbiostat.github.io/MATH315/lecture/321_Bridge.html


--->