---
title: "Class Projects"
output: 
  html_document: 
    toc: yes
    toc_float: yes
---

## Overview

Projects this semester will be user generated. They must entail a sufficient amount of data exploration and modeling, and require some sort of modeling technique that we cover in this class (missing data, survival data, clustered or correlated data, classification/prediction, multivariate analysis.)

* Graduate research? 
* Senior project? 
* Have an advisor with data/questions to ask and not enough time to investigate?
* Just want to poke around with some data and see what you can find out? 
* The subject field is up to you! 

## Deliverables

This is a birds eye check list. Details for each stage are below.  

* Week 2:`r emo::ji("hourglass")` Project proposal to Dr. D.
* Week 3: Team recruitment video
* Week 4: Project selection
* Week 5: Team formation. Groups write up team agreements, task distributions, and a project timeline
* Week 10:  Project update I (Written summary + Presentation), [Evaluation of progress towards effective team functioning](https://norcalbiostat.github.io/MATH456/notes/Effective-Teams.pdf)
* Week 14: Project presentation draft of slides + peer review
* Week 16: Project presentations, participation during final, peer rating of individual team members

## Learning objectives

Participating in this project will provide practical experiences in

* Practice team collaboration skills.
* Writing project proposals, explaining your ideas to others
* Convincing others your idea is worth their time. 
* Data wrangling
* Advanced statistical analysis topics
* Presentation (oral and written)
* Creating a project timeline/deadlines. Meeting deliverable deadlines

## Reading

* [Being an effective group member](notes/Being-an-Effective-Group-Member.pdf)
* [Turning Student Groups into Effective Teams](notes/Effective-Teams.pdf)
* [Giving constructive feedback](notes/giving-feedback/pdf)
* [The psychology of Criticism](notes/psychology-of-criticism.pdf)
* [Effective phrase templates to give criticism](notes/eff-phrase-template-criticism.pdf)

----

# Written Proposal

A 1 page written summary of your research topic due to Dr. D for approval that includes the following information. 

* Purpose: Senior project, graduate thesis, independent research, just for fun
* How much work you have done already on this analysis. 
* Data source: If the internet, you must provide a link, a codebook and/or a sample of the data. 
* Data sample: I want to *see* the raw data you intend to analyze. 
* The research question(s) at hand
* What statistical analyses topic that we cover this semester is this aligned with? 
* What you hope to accomplish, i.e. how will you use your team time? 


# Team Recruitment

## Recruitment pitch video

* Put any supplemental materials (such as your edited/revised project proposal and any sample data) in an appropriately named folder in our shared Google Drive (under `projects`)
* Create a ~5 minute "elevator pitch" video about your data and project. Be very clear what your goals are. 
* Upload this video to either A) our Google drive or B) YouTube
    - Post the link in the #project Discord channel by the due date. 
  
I will post at least one external collaborator proposal to ensure that there are enough projects to go around. These may be slightly more "work intensive" given that you won't have a subject matter expert as a team lead, but you will benefit from engaging in a much more realistic consulting experience. This is what you will often experience in the workforce as an analyst.

## Project Selection

* Use this link [this]() to choose your top six projects. 
    - **All students** must select three projects to work on. 
* Not all projects will be "funded" 
    - not all projects will have enough interest from other students to warrant a team

## Team assignment

Small teams (2-3) will be formed to work on these projects throughout the semester. 

* I will try my absolute best to assign people to the project they are most interested in. 
* You will have your own private Discord channel and a Google Drive folder for you to collaborate in.
* The project lead (the person with the data) is responsible for keeping the analysis moving forward, educating their teammates on the scientific context of the research, responsible for the majority of the contextual writing. 
* Project members are responsible for asking questions to understand the scientific context, providing assistance with programming and analysis, writing the data analysis and results sections of the report 
* If you are working with an external collaborator there is a slightly reduced expectation for a clear explanation as to the implications of your research (and other domain specific information). You will need to arrange regular meeting times with them. I will facilitate the initial meeting to make some ground rules clear that protect both them, and your, expectations and workload. 

You will mostly work outside of class on your projects throughout the semester, but I will try to schedule some collaboration time in class. 


# Team Agreements

First read the teamwork papers linked at the top of this page. Then complete the following: 

1. Create a folder in Google Drive under Projects, for your project. 
2. Using the template form in the back of the Effective Team paper, submit a _Team expectations agreement_ to your project folder in Google Drive. 
3. **_something about milestones_**

# Project Update

By the due date, 

1) Submit a 1-2 page project update summary to your project folder in Google Drive. 
    - Name this file: `Project Update Summary` so we can find it easy. 
        - If you have a slide presentation, you can name that `Project Update Summary presentation` so that they sort together. 
    - You can use either a Rmd --> PDF file, or a Google Doc. 
    - Briefly remind the reader what your project is about. 
    - Introduce the data, explain what you've done with it so far, and what you plan on doing with it in the next 4 weeks. 
    - Think of this as a script for your presentation. 
    - You can create slides if you think it will help your presentation. 
    
  
2) Present a 5-7 minute project presentation to your classmates.
    - You will be placed in 'breakout rooms' with 1-2 other groups. I will help you keep time. 
    - You will have 3 minutes for questions
    
3) When not presenting, you will be responsible for writing up a brief summary (1 paragraph) of the other groups research. E.g. Summarize in your own words what research this team is doing. What are their goals, what is their progress to date, etc. 
    - Submit your review using [[this form]](https://forms.gle/PmkDGTuphoSgqnfPA)
    - Be prepared to ask them at least one question. You could write this as a comment on their report or slides in Google Drive. 
      You can also ask them during the presentation as long as you are under the time limit. 

4) Each person individually submits [Evaluation of progress towards effective team functioning](https://norcalbiostat.github.io/MATH456/notes/Effective-Teams.pdf) using [[this form]](https://forms.gle/TjyqkDKbkM92zjDx6).


# Draft slides

You will start drafting a set of presentation slides that you will present during finals week. 

1) Create a slide deck in the `project/_Presentations` folder in Google Drive. 
  - You could use [Rmarkdown to create a slide deck](https://support.rstudio.com/hc/en-us/articles/200486468-Authoring-R-Presentations), but you'll need to make sure there is a way to add comments. 
  - Sections: 
      - Intro/Background
      - Research question/goal
      - Data introduction
      - Data preparation
      - Analysis methods
      - Results
      - Conclusion
2) Each person will review one group's slides and provide feedback using the same peer review guidelines that are used for the homework.

---

# Final Presentation

## Presentation Logistics 

Each team will present their analysis as a 10-15 minute presentation with slides. Presentation times are listed below. 

* You are not required to attend both sessions, but you are more than welcome to. It's always nice to have an audience that isn't forced to be there because they're also presenting.
* Presentations will be recorded and shared in our google drive. If you loose connection in the middle of the presentation, you will be expected to watch the rest on your own time and submit an evaluation. 
  
### Practice!
* It is *HIGHLY* recommended that you practice your presentation. 
* You will be co-presenting with people not in the same room. Your transitions need to be practiced. 
* Who will control the slides/share screen? Will this change? 
* You must stay under 12 minutes with 2-3 minutes for questions. I will cut you off and your presentation score will suffer. 
* All presenters must be able to answer questions from the audience. One person cannot dominate answering all questions. 
* This is a professional presentation. No PJ's/blankets. Don't lay down in your bed. I know we're all at home, but do your best at professionalism. 

## Participation Expectations
When you are not presenting, you are expected to pay attention and ask relevant questions. This give the presenters a chance to show what they know. 
    
    
## Grading
Each student will be responsible for two items.  

1. A score for _all other_ presentations given on the same day as their presentation. 
    - This will factor into the group grade
    - The evaluation criteria can be found at the bottom of this page. 

2. A peer rating of each other team member. This is confidential, but will be factored into the individual grades. [[Evaluation form]](https://forms.gle/Fs1k4Mi6VZeU5cCBA)

### Presenation Evaluation Criteria
I use the following criteria to score posters. Your final score is a weighted average of my score (70%),  your peers scores (30%) along with any adjustments necessary based on the individual peer ratings. This last piece is to ensure no free loading is rewarded. 

The scoring form can be found [[at this link]](https://forms.gle/eUYGZqWuMzD5zX2c6). You will have time between presentations to fill this out. 
    
* **Appearance**
    - Display attracts viewer's attention.
    - Words are easy to read.
    - Presentation is well organized and easy to follow.
    - Graphics and other visuals enhance presentation.
* **Content**
    - Purpose of model (question being addressed) is stated clearly.
    - I understand why someone might be interested in the model results.
    - There is enough detail about methods (e.g., creating new variables) for me to understand the model and results.
    - The sample characteristics are fully described.
    - The approach taken is appropriate for the problem and technically sound.
    - Conclusions are stated clearly and supported by model results.
* **Presentation** 
    - Presenter's response to questions demonstrated knowledge of subject matter and project
    - The presenters conducted themselves professional during the presentation.
    - The presentation was smooth, within time and practiced. 
    - It was clear that all team members understood what was being presented and had an equal contribution to the data analysis. One member did not dominate the presentation and questions.
    
    




----
_Last Updated: `r format(Sys.time(), "%a %b %d %X")`_
