---
title: 'Syllabus for MATH 456 - Applied Statistics II'
author: "Spring 2023"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

# Course Description
_Advanced topics in applied statistics including multiple regression, multivariate methods, nonparametrics, analysis of covariance, bootstrap methods and others as appropriate. Statistical computer packages are introduced and used. Appropriate for biology, agriculture, nutrition, business, psychology, social science and other majors._

# Logistics

**Instructor:** Dr. Robin Donatello  (Dr. D, she/her/hers)  
**Office Location:** Holt 202  
**Telephone:** 898-5767    
**E-mail:** rdonatello@csuchico.edu    
**Office Hours:** MWF 1-2pm Holt 202, or [by appointment](https://dr-donatello.youcanbook.me/).  
**Class days and times:** MWF 3-3:50, Holt 291  
**Prerequisites:** MATH 314/315/615 at Chico State or instructor permission.  
**Course Website:** http://norcalbiostat.github.io/MATH456/  
**Class chat** Chico State Math & Stats Discord server. Hw0 has the sign up instructions  
**Google Drive**  You will be added to the Math 456 Google drive using your campus email. 

This is an in person class with no expectation for hybrid learning. Synchronous zoom room can be setup (link in Canvas) in case of illness (Please don't come to class sick), but you may miss out on in class activities. 

# Learning Outcomes
Upon successful completion of this course, students will be able to:  

* Prepare data for analysis by cleaning and transforming raw data. 
* Perform research in a reproducible manner. 
* Apply advanced statistical analysis methodologies to complex and multivariate data. 
* Appropriately conduct an analysis in the presence of missing data. 
* Report the results of the analysis in plain language. 


# Required Materials
* **Textbook**: _Practical Multivariate Analysis 6th Edition_. Afifi, May, Donatello, Clark ISBN-13: 978-1138702226 
  - 6th edition is necessary
  - Several copies are available in the library. More can be made available if needed. 
* **Reliable Laptop**: Expect to bring often. Contact me if this poses a problem or concern for you. 
* **Reliable internet** connection while on and off campus. ITSS can help you get this setup. 
* **Computer Software:** Unless you have been granted an exception, all work is be done in R. Exceptions are granted on an individual basis after demonstration of proficiency in an alternate language and the ability to produce a reproducible PDF report similar to a R Markdown file and produce readable & annotated code.

# Tentative topic list

* Multiple Linear Regression Model building 
    - categorical variables, reference coding
    - moderators, confounders, interactions, stratification
    - Variable selection methods
* Classification & Prediction
    - Sensitivity/specificity/accuracy
* Multivariate statistics / Dimension Reduction
    - Principle Component Analysis
    - Factor Analysis
* Missing Data: Identification & Imputation
* Additional Topics. 1-2 of the following topics will also be covered. 
    - Cluster analysis
    - Analysis of Survival Data
    - Generalized linear models / modeling of count data. 
    - Correlated outcomes (Multi-level models)
    - Bootstrap methods


# Assignments / graded items 
Your final grade will be a straight sum of points earned and will be displayed as a running total in Canvas. 
I use a standard grade cutoff of 100-90%: A, 89-80%: B, 79-70%: C, 69-60%: D, 0-59%: F  


#### Exams (25%)
* 2 Exams (midterm/final, not cumulative). [Error Assessment Form](notes/Analyzing exam errors.pdf) available for midterm. 

#### Assignments (30%)
* 6 Standard homework assignments on the topics listed above. Drafts submitted through Google Drive, Final versions for grading submitted through Canvas. 

#### Quizzes (15%)
* Nearly weekly Individual + Group quizzes. Administered through Google Forms. Lowest score dropped. 

#### Active Learning (30%)
* Various active or reflective [learning activities](learning_tools.html) during/outside of class.
* Peer reviews (PR) of assignments. Because helping others helps you learn. 
* Attending [Community Coding](http://bit.ly/cc_hours) and/or Office Hours **2** times. This can be to check in on your grade, ask clarifying questions, or chat about life and graduate school.
* Discord participation. Contributing to our learning community by asking and answering questions about assignments, code, etc in Discord is required to make this class run smoothly. And in the end, you are the ones that will benefit from it the most. Don't spend more than 20 min banging your head on the proverbial wall before you reach out and ask for help. 
* One external activity. Because no academic topic only lives in the classroom. Examples include:
    -  Attending an internal/external seminar talk on a topic in Applied Statistics, or a Data analysis-centric seminar talk, writing a 1 page summary about the talk and how it relates to this class or your chosen field, and sharing this summary in the #external-learning Discord channel.
    - Contribute to the [Applied Statistics Course Notes](https://norcalbiostat.github.io/AppliedStatistics_notes/). This could be a new example or  enhancing/fixing an old example
        - Once you identify the piece you want to work on, PM me the section in Discord I will send you the relevant code/data. 


----

# Class Policies and statements

## Everyone is welcome here

It is my intent that students from all diverse backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength and benefit. It is my intent to present materials and activities that are respectful of diversity: gender identity, sexuality, disability, age, socioeconomic status, ethnicity, race, nationality, religion, and culture. Your suggestions are encouraged and appreciated. Please let me know ways to improve the effectiveness of the course for you personally, or for other students or student groups.

I would like to create a learning environment that supports a diversity of thoughts, perspectives and experiences, and honors your identities (including race, gender, class, sexuality, religion, ability, etc.) To help accomplish this:

-  Let me know if you have a name and/or set of pronouns that differ from those that appear in your official Chico records. I make it a point to call on people by name, so please make sure that I know what you want to be called. 
        - I also want to try to pronounce your name as accurately as possible. The more you help and correct me the better I can do to honor your name. 
-   If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. I want to be a resource for you. Remember that you can also submit anonymous feedback using the feedback button on the schedule and help pages of the website (which will lead to me making a general announcement to the class, if necessary to address your concerns).
-   If you prefer to speak with someone outside of the course, the Office of Diversity and Inclusion is here to assist. Their number is 530-898-4764, and email [diversityoffice\@csuchico.edu](mailto:diversityoffice@csuchico.edu){.email}
-   I (like many people) am still in the process of learning about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please talk to me about it. (Again, anonymous feedback is always an option).

*Adapted from [Monica Linden at Brown University](https://www.brown.edu/sheridan/teaching-learning-resources/inclusive-teaching/statements)*.

Furthermore, I would like to acknowledge that Chico State stands on lands that were originally occupied by the first people of this area, the Mechoopda. I recognize their distinctive spiritual relationship with this land and the waters that run through campus. I am humbled that our campus resides upon sacred lands that once sustained the Mechoopda people for centuries.



## Attendance

Class attendance is expected. Talk to me ahead of time if you need to miss a class for a planned reason. In the event of an unplanned reason, DM me in Discord when you can so that I know you are still alive. 

* If you are not feeling well or are experiencing Covid symptoms **DO NOT COME TO CLASS**. DM me in Discord we'll make a backup plan. 


## Late work
* You should strive to submit on time for all draft items the sake of your peers. Do you want your reviews back in a timely manner? You should show them the same courtesy and professionalism. 
* I don't penalize for late work, but I prioritize on time submissions. If you submit an assignment after i'm done grading everyone elses, and we're moving on to the next topic then your assignment may have to wait a long time before I can get back to it. 

## Collaboration

Collaboration on assignments is encouraged. People learn better when they have someone else to talk through concepts with. 

:::{.callout-warning}
Collaboration on exams is not allowed.
:::

----

# Student Resources

## Chico State Basic Needs Project

The **Hungry Wildcat Food Pantry** provides supplemental food, fresh produce, CalFresh application assistance and basic needs referral services for students experiencing food and housing insecurity.

All students are welcomed to visit the Pantry located in the Student Service Center 196, open Monday-Friday

Please visit the Chico State Basic Needs website [http://www.csuchico.edu/basic-needs](http://www.csuchico.edu/basic-needs) for more information.

## Wildcat Computing Support

Everyone's journey through education is different and varied. Part of your journey is learning to engage and leverage academic technology. It is extremely important to your success, and at the same time requires patience to learn how it can benefit you. While learning various technologies, they change and adapt quickly. Wildcat Computing Support is curated by students to better support you and enhance your experiences with technology. We provide information to support your success in using academic technology in and out of the classroom.

[https://www.csuchico.edu/wcs/](https://www.csuchico.edu/wcs/)


## Americans with Disabilities Act

If you need course adaptations or accommodations because of a disability or chronic illness, or if you need to make special arrangements in case the building must be evacuated, please make an appointment with me as soon as possible, or see me during office hours. Please also contact Accessibility Resource Center (ARC) as they are the designated department responsible for approving and coordinating reasonable accommodations and services for students with disabilities. ARC will help you understand your rights and responsibilities under the Americans with Disabilities Act and provide you further assistance with requesting and arranging accommodations. We try our best to ensure equal access to materials in accessible formats. Reach out to your me if there is some aspect of the course materials that are inaccessible to you.

Accessibility Resource Center 530-898-5959 Student Services Center 170 [arcdept\@csuchico.edu](mailto:arcdept@csuchico.edu){.email} [http://www.csuchico.edu/arc](https://www.csuchico.edu/arc/)

----

# University Policies

## COVID-19 

The CSU requires students to be fully vaccinated and boosted against COVID-19 by February 28th, 2022, unless you have an approved exemption. While Chico State has relaxed its stance on mask mandates, for your and my health and safety I _request_ that everyone wear an appropriate face mask covering the nose and mouth while in class. 

## Adding and Dropping the course

You are responsible for understanding the policies and procedures about add/drops, academic renewal, etc., found in the [CSU Chico University Catalog](http://www.csuchico.edu/catalog/). You should be aware of the new deadlines and penalties for adding and dropping classes.

## Confidentiality and Mandatory Reoprting

As an instructor, one of my responsibilities is to help create a safe learning environment on our campus. I also have a mandatory reporting responsibility related to my role as a your instructor. I am required to share information regarding sexual misconduct with the University. Students may speak to someone confidentially by contacting the Counseling and Wellness Center (898-6345) or Safe Place (898-3030). Information on campus reporting obligations and other Title IX related resources are available here: www.csuchico.edu/title-ix.


## Academic Integrity

Academic integrity is defined as “a commitment, even in the face of adversity, to five fundamental values: honesty, trust, fairness, respect, and responsibility”. From these values flow principles of behavior that enable academic communities to translate ideals to action. Academic integrity is expected and required. No forms of cheating or plagiarism will be tolerated. Please see your student handbook at https://www.csuchico.edu/scrr/integrity.shtml if you have questions about the meaning of these terms or the consequences of violating academic integrity.

-----

_Last updated: `r format(Sys.time(), "%a %b %d %Y %X")`_