---
title: "MATH 456: Applied Statistics II (Sp18) Syllabus"
output:
  pdf_document: default
---

# Course Information

**Instructor:** Dr. Robin Donatello  
**Office Location:** Holt 202  
**Telephone:** 898-5767    
**E-mail:** rdonatello@csuchico.edu    
**Office Hours:** TBD Week 2  
**Class days and times:** MWF 9-10:50, Holt 155  
**Prerequisites:** MATH 315/615 at Chico State or instructor permission.  
**Course Website:** http://norcalbiostat.github.io/MATH456/ 

## Course Description and Goals
From the CSUC Course Catalog: Advanced topics in applied statistics including multiple regression, multivariate methods, nonparametrics, analysis of covariance, bootstrap methods and others as appropriate. Statistical computer packages are introduced and used. Appropriate for biology, agriculture, nutrition, business, psychology, social science and other maojrs. 3 hours discussion.

Click [[here]](Syllabus_S18.pdf) for a PDF version of this syllabus. 

## Course Content Learning Outcomes
Upon successful completion of this course, students will be able to:  

* Translate a research question into an appropriate statistical analysis plan. 
* Prepare data for analysis by cleaning and transforming raw data. 
* Perform research in a reproducible manner. 
* Build statistical models to examine real processes. 
* Report the results of the analysis in plain language. 


## Required Materials
#### Textbooks
Practical Multivariate Analysis 5th Edition. Afifi, May, Clark ISBN 9781439816806  
You can use the promo code **LEARN** at www.crcpress.com  to save 25% off of the textbook or any other CRC Press book they need for the semester. This special, student discount is only available through this offer for the upcoming spring semester.

#### Computer Hardware and Software 
We will be using the statistical programming language R. You are expected to have prior experience with this language. 
Loaner laptops will be available for you to use during class time only. These systems will be set up properly and ready to go on day 1. You will eventually have to set up and bring your own laptop to class. There will not be sufficient time during class for you to complete the necessary work. All software programs we will use are free.  


**If you have no prior experience with R you have some choices.**

1) Go through any number of self-paced free online tutorials. Recommended ones are [DataCamp](https://www.datacamp.com/courses/free-introduction-to-r), [TryR](http://tryr.codeschool.com/), and [R Tutorial](http://www.r-tutor.com/r-introduction).
2) Enroll in MATH 130 (Math 130-01 - Week 1-5 only TR 9:30-11am BUTTE 211)


## Online Component
* All course materials can be found on the [course website](http://norcalbiostat.github.io/MATH456/). 
* You are responsible for regularly checking this website for updates and announcements.
* The daily class [schedule](Schedule.html) can be found on the class website.
* It is your responsibility to be aware of the current schedule.

# Tentative topic list

* Multiple Linear Regression (partial review)
    - Model building / fit
    - log transforming outcomes
    - moderators, confounders, interactions, stratification
    - categorical variables, reference coding, contrasts
* Logistic Regression
    - Odds Ratios and Risk Ratios
    - Used as a classifier
    - Sensitivity/specificity/accuracy
* Multivariable statistics / Dimension Reduction
    - Principle Component Analysis
    - Factor Analysis
* Multilevel (hierarchical) models
    - Clustered data
    - Longitudinal data
    - Spatial data
* Missing Data: Identification & Imputation
    
    
# Grading

* There are 460 points available. The breakdown is as follows: 
    - Assignments (120), Learning (90), 2 Exams (200), Project (50)
    - Both exams will be broken into part take home and part in class. 
    - **Any cheating observed on the take home portion of either exam will result in a 0 score**
    _ _points are subject to change_
* I use a standard grade cutoff of 100-90%: A, 89-80%: B, 79-70%: C, 69-60%: D, 0-59%: F Plusses and minuses will be as displayed on Blackboard Learn. 

# Other Logistics

## Adding and Dropping the course
The last day to drop or add a course is 2/16/18. After this date, withdraws will only be allowed for serious and compelling reasons subject to department chair approval.

## Americans with Disabilities Act
If you need course adaptations or accommodations because of a disability or chronic illness,  or if you need to make special arrangements in case the building must be evacuated, please make an appointment with me as soon as possible, or see me during office hours. Please also contact Accessibility Resource Center (ARC) as they are the designated department responsible for approving and coordinating reasonable accommodations and services for students with disabilities. ARC will help you understand your rights and responsibilities under the Americans with Disabilities Act and provide you further assistance with requesting and arranging accommodations.

Accessibility Resource Center  
530-898-5959   
Student Services Center 170  
arcdept@csuchico.edu  


_Last updated: `r format(Sys.time(), "%a %b %d %Y %X")`_

    
    
