---
output:
  html_document:
    highlight: tango
    theme: journal
    toc: yes
    toc_float: yes
css: css/style.css
title: "Week 1: Jan 22 - Jan 28"
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr);library(readxl); library(knitr)
library(kableExtra); library(stringr)
knitr::opts_chunk$set(echo = FALSE)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```
<br>

_Last Updated: `r format(Sys.time(), "%a %b %d %X")` _
<br>


```{r echo=FALSE, message=FALSE, warning=FALSE}
raw <- read_excel("schedule_456.xlsx")
week.w <- filter(raw, Week==1)

topics <- str_split(week.w$Topics, ",", simplify=TRUE)
SLO    <- t(str_split(week.w$SLO, "\r\n", simplify=TRUE))
prep   <- t(str_split(week.w$Prepare, "\r\n", simplify=TRUE))
mats   <- t(str_split(week.w$Materials, "\r\n", simplify=TRUE))
hw     <- t(str_split(week.w$Assignments, "\r\n", simplify=TRUE))
mon    <- t(str_split(week.w$Monday, "\r\n", simplify=TRUE))
wed    <- t(str_split(week.w$Wednesday, "\r\n", simplify=TRUE))
fri    <- t(str_split(week.w$Friday, "\r\n", simplify=TRUE))
```

----

# Learning Objectives
```{r}
kable(SLO) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

# Prepare
```{r}
kable(prep) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

* If your Slack account uses your @csuchico.edu email, you should be able to search for the workspace and add yourself.
* The Slack phone app is technically optional, but really really helpful/handy. Students historically have stated it's much easier to work with. If you opt out of the phone app, make sure the program is installed onto your laptop. You need to be connected throughout the semester, not just when you remember to log in. 

<br>

# Materials
```{r}
kable(mats) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

# Assignments
```{r}
kable(hw) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

### Data Camp Assignment
* Your goal is to collect around 25,000 XP from any course in Data Camp. This is approximately 5 classes. 
* You have all semester to do so. I will assign midterm progress points around Spring Break. 
* Your past work does not count. 
* I highly recommend that you engage in a skill track to do this.  https://www.datacamp.com/tracks/skill 
* You are not limited to learning R! Use this time to pick up on Python if you like.

----

# Monday: `r topics[1]`

```{r}
kable(mon) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

Rules for producing questions: 

1.	Ask as many questions as you can
2.	Do not stop to answer, judge or to discuss the questions
3.	Write down every question _exactly_ as it is stated
4.	Change any statement into a question


# Wednesday: `r topics[2]`

```{r}
kable(wed) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

# Friday: `r topics[3]`

```{r}
kable(fri) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


