---
output:
  html_document:
    highlight: tango
    theme: journal
    toc: yes
    toc_float: yes
css: style.css
title: "Week 2: Jan 29- Feb 4"
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr);library(readxl); library(knitr)
library(kableExtra); library(stringr)
knitr::opts_chunk$set(echo = FALSE)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```
<br>

_Last Updated: `r format(Sys.time(), "%a %b %d %X")` _
<br>


```{r echo=FALSE, message=FALSE, warning=FALSE}
raw <- read_excel("schedule_456.xlsx")
week.w <- filter(raw, Week==2)

topics <- str_split(week.w$Topics, ",", simplify=TRUE)
SLO    <- t(str_split(week.w$SLO, "\r\n", simplify=TRUE))
prep   <- t(str_split(week.w$Prepare, "\r\n", simplify=TRUE))
mats   <- t(str_split(week.w$Materials, "\r\n", simplify=TRUE))
hw     <- t(str_split(week.w$Assignments, "\r\n", simplify=TRUE))
mon    <- t(str_split(week.w$Monday, "\r\n", simplify=TRUE))
wed    <- t(str_split(week.w$Wednesday, "\r\n", simplify=TRUE))
fri    <- t(str_split(week.w$Friday, "\r\n", simplify=TRUE))
```

----

# Learning Objectives
```{r}
kable(SLO) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

#Prepare
```{r}
kable(prep) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

# Materials
```{r}
kable(mats) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

# Assignments
```{r}
kable(hw) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

**Multiple Regression assignment:**

* Using the NCbirths data set
    * Model birthweight using mothers age, smoking habit, and number of visits. 
    * Calculate and interpret a 95% prediction interval for a 30-year old smoking mother with 16 visits to the doctor during her pregnancy. 
    * Does smoking habit affect the relationship between age and birthweight? 
* PMA5: Ex 7.5, 7.6, 7.15, 7.17
* Knit to Word or PDF and submit through Blackboard learn by the due date. 

**Model Building Report:**

In a separate RMD document: 

* Build a model to predict the age in which an adolescent starts smoking. 
    - Come up with two competing models and compare them on at least two measures of fit. 
* Describe your steps along the way as if you were writing a report. 
    - This includes describing any data management along the way. 
* Knit to PDF, use section level headers to organize your report. 
* This will be peer reviewed. 
* Upload your final PDF document to the `Model Building` folder in our class Google Drive. Name your file with your username. e.g. _modeling_startsmoke_rdonatello.pdf_


----

# Monday: `r topics[1]`

```{r}
kable(mon) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```



# Wednesday: `r topics[2]`

```{r}
kable(wed) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```



# Friday: `r topics[3]`

```{r}
kable(fri) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


