---
output:
  html_document:
    highlight: tango
    theme: journal
    toc: yes
    toc_float: yes
css: style.css
title: "Week 3: Feb 5 - Feb 11"
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr);library(readxl); library(knitr)
library(kableExtra); library(stringr)
knitr::opts_chunk$set(echo = FALSE)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```
<br>

_Last Updated: `r format(Sys.time(), "%a %b %d %X")` _
<br>


```{r echo=FALSE, message=FALSE, warning=FALSE}
raw <- read_excel("schedule_456.xlsx")
week.w <- filter(raw, Week==3)

topics <- str_split(week.w$Topics, ",", simplify=TRUE)
SLO    <- t(str_split(week.w$SLO, "\r\n", simplify=TRUE))
prep   <- t(str_split(week.w$Prepare, "\r\n", simplify=TRUE))
mats   <- t(str_split(week.w$Materials, "\r\n", simplify=TRUE))
hw     <- t(str_split(week.w$Assignments, "\r\n", simplify=TRUE))
mon    <- t(str_split(week.w$Monday, "\r\n", simplify=TRUE))
wed    <- t(str_split(week.w$Wednesday, "\r\n", simplify=TRUE))
fri    <- t(str_split(week.w$Friday, "\r\n", simplify=TRUE))
```

----

# Learning Objectives
```{r}
kable(SLO) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

#Prepare
```{r}
kable(prep) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

# Materials
```{r}
kable(mats) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

# Assignments
```{r}
kable(hw) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

**Peer Review instructions**

* Use the `Peer Review Rotation` spreadsheet in our class Google Drive to find out who you are assigned to review. 
    - Download those reports and read through them.
    - Provide 4 total comments using the commenting feature directly in Adobe. 
        - Two things that they could have done better. 
        - Two things that they did well. 
* Name your reviewed copy with your username and upload back to the Model building folder. 

> model_startsmoke_rdonatello_reviewername.pdf

* After the peer review due date you should download your reviewed assignments and read the comments. 


    



----

# Monday: `r topics[1]`

```{r}
kable(mon) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


# Wednesday: No Class Meeting 

```{r}
kable(wed) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


# Friday: `r topics[3]`

```{r}
kable(fri) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


