---
output:
  html_document:
    highlight: tango
    theme: journal
    toc: yes
    toc_float: yes
css: style.css
title: "Week 11: Apr 9 - Apr 15"
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr);library(readxl); library(knitr)
library(kableExtra); library(stringr)
knitr::opts_chunk$set(echo = FALSE)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```
<br>

_Last Updated: `r format(Sys.time(), "%a %b %d %X")` _
<br>


```{r echo=FALSE, message=FALSE, warning=FALSE}
raw <- read_excel("schedule_456.xlsx")
week.w <- filter(raw, Week==11)

topics <- str_split(week.w$Topics, ",", simplify=TRUE)
SLO    <- t(str_split(week.w$SLO, "\r\n", simplify=TRUE))
prep   <- t(str_split(week.w$Prepare, "\r\n", simplify=TRUE))
mats   <- t(str_split(week.w$Materials, "\r\n", simplify=TRUE))
hw     <- t(str_split(week.w$Assignments, "\r\n", simplify=TRUE))
mon    <- t(str_split(week.w$Monday, "\r\n", simplify=TRUE))
wed    <- t(str_split(week.w$Wednesday, "\r\n", simplify=TRUE))
fri    <- t(str_split(week.w$Friday, "\r\n", simplify=TRUE))
```

----

# Learning Objectives
```{r}
kable(SLO) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

#Prepare
```{r}
kable(prep) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

# Materials
```{r}
kable(mats) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

# Assignments
```{r}
kable(hw) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```
<span style="color:red">**Don't forget to submit your poster abstract by 4/16!**</span>.


#### Spatio-Temporal Assignment: Part I 

1. Replicate Figure 18.4 in the PMAS textbook on pg 483. Either color the points or change the shape of the points depending on the group. 
2. How often are the mice weighed? Does the variable `day` represent nominal or actual time? Why do you think the times are setup this way (i.e. would you expect the mice to be weighed at different times)? 
3. Visualize the correlation of weight between time points using a correlation matrix. Does it appear that the correlation is lower between further away time points? 
4. Model the weight of a mouse using day as a predictor and using a random intercept model to account for the correlation within mouse. Use three different correlation structures: Independent, CS, and AR(1). Using AIC/BIC, which model provides the best fit? _Hint: Use can use the `AIC()` and `BIC()` functions on the model objects you create to calculate these measurs of fit_
5. For your best model, what is the estimate of the proportion of variance that is explained by the clusters? What is this term called? Is the correlation of weights within mouse high enough to warrent a random intercept model? **Print the raw R output of your chosen model here. Don't use stargazer/sjplot. I want to confirm that the model was fit correctly.**

----

# Monday: `r topics[1]`

```{r}
kable(mon) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


# Wednesday: `r topics[2]`

```{r}
kable(wed) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


# Friday: `r topics[3]`

```{r}
kable(fri) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


