---
output:
  html_document:
    highlight: tango
    theme: journal
    toc: yes
    toc_float: yes
css: style.css
title: "Week 12: Apr 16 - Apr 22"
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr);library(readxl); library(knitr)
library(kableExtra); library(stringr)
knitr::opts_chunk$set(echo = FALSE)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```
<br>

_Last Updated: `r format(Sys.time(), "%a %b %d %X")` _
<br>


```{r echo=FALSE, message=FALSE, warning=FALSE}
raw <- read_excel("schedule_456.xlsx")
week.w <- filter(raw, Week==12)

topics <- str_split(week.w$Topics, ",", simplify=TRUE)
SLO    <- t(str_split(week.w$SLO, "\r\n", simplify=TRUE))
prep   <- t(str_split(week.w$Prepare, "\r\n", simplify=TRUE))
mats   <- t(str_split(week.w$Materials, "\r\n", simplify=TRUE))
hw     <- t(str_split(week.w$Assignments, "\r\n", simplify=TRUE))
mon    <- t(str_split(week.w$Monday, "\r\n", simplify=TRUE))
wed    <- t(str_split(week.w$Wednesday, "\r\n", simplify=TRUE))
fri    <- t(str_split(week.w$Friday, "\r\n", simplify=TRUE))
```

----

# Learning Objectives
```{r}
kable(SLO) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

#Prepare
```{r}
kable(prep) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

# Materials
```{r}
kable(mats) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

# Assignments
```{r}
kable(hw) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


#### Spatio-Temporal Assignment: Part II (Due Sunday 4/20. Peer Review Due Wed 4/22)
This part of the assignment uses two data sets: 

* [[ozone.txt]](notes/ozone.txt) contains hourly ozone levels for censor locations in Southern California measured on three different days. 
* [[ozone_cities.csv]](notes/ozone_cities.csv) contains polygon data for cities near the censor locations. 

Data preparation steps: 

* Rename `oz_name` to `fullname` for merging purposes. 
* In `ozone`, the longitude data is positive (wrong hemisphere.) Change these numbers to negative. 
* Create a new data set called `sensors` from the `ozone` data , that only keeps one record for each site, and only keeps variables: `site`, `lat`, `long`. _Hint: The `unique()` function will be helpful here_

1. Create a plot of SoCal with sensor locations, nearby cities, and the population of those cities.
    a. Use `get_map` to download a raster (image) map centered around the average lat/long of the sensor location. A zoom of 9 is good.  
    b. Use `ggmap` to create the plot, add points for stations, and polygons for the city shapes. (_Yes there will be wierd lines in here. I will talk about that in class_)
    c. Fill the polygons by `log(Pop201)`. Set the `alpha` value in the polygons to be < 1 so that the shapes are translucent.  
2. Calculate the max ozone level per region. 
    - Join this new variable onto the polygon data frame. It is advised to make a new data frame for this point. 
    - Map the max ozone level per region using a continuous scale that goes from red to black. 
    - Add a title. 
    - You don't need to add sensor points here. 
    - **Describe any spatial patterns you see. What do you think is contributing to this pattern? **
3. Calculate the max ozone per site, per hour for the following hours: 7am, 12 noon, 3pm 6pm. 
    - _Hint: Filtering `ozone` prior to `group_by` will simplify the merging._
    - Merge this summary data onto the sensor data 
    - Create 4 plots (`morning`, `noon`, `afternoon`, `evening`) - on each one plot the max ozone for the specified time frame only. 
    - Use `grid.arrange` to make a 2x2 grid of maps. 
    - **Describe any spatial or temporal patterns you see. What do you think is contributing to this pattern? A few google searches here may be helpful: keywords topography, inversion layer, offshore winds, pollution, southern california**
4. Look carefuly at the legends. Redraw the above group of plots on the same scale by providing a `limits=c(low, high)` argument to `scale_fill_continuous()`. **How does this change your answer to the above question? Is one display "better" than the other?**
5. Identify neighbors as cities that have sensors within X miles of each other. 
    - Use the functions found in notebook 13.3.3 and play around with X until you find a value that seems to match the patterns seen in the ozone plots. _Not all cities will connect_
    - Create a new plot that connects the neighboring cities with a line. _Hint: You'll need to copy that `nb_to_df` function from the link in the notes._
    - **For this geographic region, is distance measured "as the crow flies" an appropriate way to identify neighbors?**

----

# Monday: `r topics[1]`

```{r}
kable(mon) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


# Wednesday: `r topics[2]`

```{r}
kable(wed) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


# Friday: `r topics[3]`

```{r}
kable(fri) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


