---
output:
  html_document:
    highlight: tango
    theme: journal
    toc: yes
    toc_float: yes
css: style.css
title: "Week 15: May 7 - May 11"
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr);library(readxl); library(knitr)
library(kableExtra); library(stringr)
knitr::opts_chunk$set(echo = FALSE)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```
<br>

_Last Updated: `r format(Sys.time(), "%a %b %d %X")` _
<br>


```{r echo=FALSE, message=FALSE, warning=FALSE}
raw <- read_excel("schedule_456.xlsx")
week.w <- filter(raw, Week==15)

topics <- str_split(week.w$Topics, ",", simplify=TRUE)
SLO    <- t(str_split(week.w$SLO, "\r\n", simplify=TRUE))
prep   <- t(str_split(week.w$Prepare, "\r\n", simplify=TRUE))
mats   <- t(str_split(week.w$Materials, "\r\n", simplify=TRUE))
hw     <- t(str_split(week.w$Assignments, "\r\n", simplify=TRUE))
mon    <- t(str_split(week.w$Monday, "\r\n", simplify=TRUE))
wed    <- t(str_split(week.w$Wednesday, "\r\n", simplify=TRUE))
fri    <- t(str_split(week.w$Friday, "\r\n", simplify=TRUE))
```

----

# Learning Objectives
```{r}
kable(SLO) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

#Prepare
```{r}
kable(prep) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```

#### Presentation Content
This is about the statistical methodological process, not results. Your goal is to fully explain to me the following: 

* What your research question is. 
* What general type of data you used to answer this question (i.e. survey data, fly counts, state characteristics)
    - where the data came from
    - any concerns/problems with the data. 
* What pre-processing you had to do and why what you did was justified. I do not want to hear "We turned missing data into NA's". `NA` is R code terminology. Tell me *what* you did with the missing data (if any) and why your actions were justified. 
* Explain your primary outcome variable, and primary covariates (if any). 
* What exploratory analysis did you perform to understand the data. 
    - Show an example (univariate and bivariate) and explain what you learned from them. 
    - What decisions did you make based on these findings? 
* What statistical model(s) did you employ to answer your research question? 
    - Why were they appropriate/justified. Don't give me stuff about residuals here, those are for post modeling validation. 
* What were the important/meaningful results obtained? 
* What conclusions did you come to based on those results? 


----

# Monday: `r topics[1]`

```{r}
kable(mon) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


# Wednesday: `r topics[2]`

```{r}
kable(wed) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


# Friday: `r topics[3]`

```{r}
kable(fri) %>% kable_styling(bootstrap_options = c("striped", "condensed"))
```


