---
title: "HW02 - Logistic Regression & Classification"
author: "MATH 456 - Spring 2020"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

# Submission Instructions. 

* I am no longer providing homework templates. 
* You should be using your cleaned version of the direct book data, not the version that you used in HW01.
* Submit your draft PDF to the Google Drive: `HW02: Logistic regression and classification/Draft` folder by the due date. 
* Read the question carefully. Some book questions require you to use appropriate variable selection techniques. 

# Part I: Logistic Regression

1. Playing with odds: PMA6 12.1
2. Logistic Regression modeling: PMA6 12.7, 12.8
3. Compare the models in part 2 for acute vs chronic illness. 
    a. Are the measures that are important in explaining the outcome similar? 
    b. For covariates that are the same, compare the effect of that covariate on each of the outcomes. 
4. Northridge Earthquake: (PMA6 12.22-12.29 modified). This problem use the Northridge earthquake data set. [[See here for more info about this event.]](https://www.google.com/search?client=firefox-b-1-d&q=northridge+earthquake+1994) We are interested in knowing if homeowners (`V449`) were more likely than renters to report emotional injuries (`W238`) as a result of the Northridge earthquake, controlling for age (`RAGE`), gender (`RSEX`), and ethnicity (`NEWETHN`). 
    a. Explore all measures in question using summary tables. Comment on any unusual values. Perform necessary data management (E.g. fix any values that are out of range, plausibly incorrect, or categories with too small sample sizes)
    b. Fit a logistic regression model on emotional injury as the outcome using the variables listed above as predictors. Use `tbl_regression` to create a nice table of results that include odds ratios and 95% confidence intervals. See if you can figure out how to drop the intercept term from the table. 
    c. Interpret each predictor (except the intercept) in context of the problem.
    d. Are the estimated effects of home ownership upon reporting emotional injuries different for men and women, controlling for age and ethnicity? That is, is there a significant interaction effect between gender and home ownership?

    
# Part II: Binary Classification
Playing Hookey (PMA6 12.18-12.19 modified)

1. Perform a binary logistic regression analysis using the Parental HIV data to model the probability of having been absent from school without a reason (variable `HOOKEY`). Find the variables that best predict whether an adolescent had been absent without a reason or not. Use a **hefty dose of common sense** here, not all variables are reasonable to use (e.g. using the # of times a student skips school to predict whether or not they will predict school)
2. Use the default value for the `predict()` function to create a vector of predictions for each student. 
3. Create a confusion matrix for these predictions and interpret: accuracy, balanced accuracy, sensitivity, specificity, PPV, NPV.
4. Create a plot of predicted probabilities by true group membership. Describe the distributions. What do you notice? 
5. Find the best cutoff point to discriminate between adolescents who were absent without a reason and those who were not by using an ROC curve and maximizing accuracy. 
6. Recreate your confusion matrix using the new cutoff point. What affect did this change have on the other metrics?  



   