---
title: "Cluster Analysis"
output:
  html_document: default
  pdf_document: default
---


# Instructions

Conduct a cluster analysis on your project (or thesis) data. The format of the homework should look like a report that addresses the following questions, within the following sections. 

* Introduction
    - This is a brief data introduction to the data.
    - _a priori_ what do you expect to find? Is there a natural grouping you expect to find in your data? 
* Data Preparation
    - Any data management that you did prior to the analysis (filtering, only choosing certain variables etc)
* Methods
    - Explain in English which clustering methods you are using. Including details such as type of distance or linkage. 
    - You must test out at least two clustering algorithms. 
    - You must explore different numbers of $k$
* Results
    - You must include plots
    - You must talk about each plot. 
* Conclusion
    - What is your take home message? How many clusters do you have? 
    - Can you interpret your clusters in context? 
    - Does anything stand out? 
    - Did you expect these results? 
    



# Submission instructions

* Name this file `hw05_cluster_username`
* Compile to PDF, make sure it looks clean and readable. 
* Use markdown headers (#, ##) to denote sections. 
* Upload to Topic 05 google drive folder by the due date. 
* You will still have a draft and final version. 
         