---
title: "Mid-semester changes"
output: 
  html_document: 
    toc: yes
    toc_float: yes
---


#### Changes to graded items

* The requirement to go to community coding is removed. 
* The requirement to contribute to the ASCN has been shifted to extra credit. 
* The number of peer reviews has been reduced from 2 to 1.
    - But the review critiera is more stringent. The [how to conduct a peer review Google Document](https://drive.google.com/open?id=1eAe2joBOQ_RGkYi9k3LPBAiaclhjLoXBJdsOu1f4xrs) has been updated to reflect these changes. 
    - Short version, 1 review, 6 comments/corrections minimum, X pts for the review. 
* There will be no final exam. 
      - Finals week will be an instructional week, and consist of project presentations. 

    
* The requirement to attend office hours is still present, but modified to bi-weekly check ins. 
    - This will be our 1:1 time to make sure you're getting the information and help you need to learn. 
    - You can sign up for times to meet using the following link: 
    
    
#### Policy changes
* Office hours have been updated as follows: 
    - MWF 2-3pm when we are not meeing asynchronously.
    - As requested by you via a message in Slack. 
* The SET's will be delivered online. This is not my choice. 
    - I trust that after our last module on missing data you are aware of the bias that can occur from non-response
    - I would ask that you be honest, but kind in your reviews. This is not easy on any of us right now and we're all doing our best. 
* Zoom Attendance
  - Friday zoom sessions will be recorded and uploaded to our Google Drive. 
  - If you have dogs, kids, family members etc at home and they want to 'join' you for class, it's fine! My dogs are gonna bark in my lecture videos, i'm not going to edit it out. It's life, and we need to give each other grace in this time. I don't care if you attend class in your PJ's with unbrushed hair. I don't even care if you are all sweaty b/c you just got back from a run or work out (while keeping a social distance), not like we'll smell ya! We each have a life outside of the classroom, and well this semester our life is going to become part of our classroom. It's okay, we'll roll with it. I'd rather see your lovely faces each week and know that you're still healthy, and willing to learn. 

### General

Please let me know if something changes in your schedule that make it difficult for you to attend the synchronous discussion. For example, if you or a family member gets sick. 

If I have missed something with the way our class was structured, or required assignments, that you think should be modified to accomodate our new meeting style please let me know. 

#### Procedural changes ("aka" How class will be run)
We have 3 more topics left, each is schedule to take 2 weeks. Each topic consists of 5 graded items: A pre-topic QFT, a written assignment, peer review of the written assignment, asynchronous discussion in Slack, and a quiz. 

These are explained in detail below. Dates are noted as [Day][Week]. So Sun1 is sunday of week 1 of that topic. Wed2 is wednesday of the second week of that topic. You can always see the actual dates on the [class calendar](https://norcalbiostat.github.io/MATH456/schedule.html). 

* Pre-topic warmup (Sun1)
    - Join the Slack discussion channel for that topic. 
    - Go through the Question Formulation Technique exercise for the upcoming topic. 
        - The slides with modified instructions can be found in the topic folder in Google Drive. 
        - I will be checking this off on Monday morning (Mon1)
    
* Week 1 topic "content delivery" via mini lecture videos. 
    - I will create multiple variable length lectures that will follow the ASCN course notes and the textbook. 
    - These videos will be uploaded to our Google Drive. 
    - They will not replace reading the textbook. 
    - Normal class time on MW is open zoom time. Link will be in Slack. 
      
* Week 1 Synchronous class time (Fri1)
    - Housekeeping/catch up/check in
    - Random group QFT report out.  
    - Open question time
  
    
* Week 1 Asynchronous work
    - Ask at least one question in the topic channel in Slack (Sat1)
    - Start the topic homework assignment. 
          
          
* Week 2 topic "content delivery" via mini lecture videos. 
* Week 2 Asynchronous work          
      - Answer, or write comments on 2 other questions or posts in Slack (Tue2)
      - Homework assignment: draft due (Tue2), Peer review due (Thu2), Final due (Sat2)
      - Individual quiz (Thu 2)
      

* Week 2 Synchronous class time (Fri2)
    - Housekeeping/catch up/check in
    - Random group quiz
    - Open question time
  