<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.319">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Marginal Effects</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="marginal_effects_files/libs/clipboard/clipboard.min.js"></script>
<script src="marginal_effects_files/libs/quarto-html/quarto.js"></script>
<script src="marginal_effects_files/libs/quarto-html/popper.min.js"></script>
<script src="marginal_effects_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="marginal_effects_files/libs/quarto-html/anchor.min.js"></script>
<link href="marginal_effects_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="marginal_effects_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="marginal_effects_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="marginal_effects_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="marginal_effects_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#making-predictions" id="toc-making-predictions" class="nav-link active" data-scroll-target="#making-predictions">Making Predictions</a></li>
  <li><a href="#adjusted-predictions-at-the-mean" id="toc-adjusted-predictions-at-the-mean" class="nav-link" data-scroll-target="#adjusted-predictions-at-the-mean">Adjusted predictions at the mean</a></li>
  <li><a href="#average-adjusted-predictions-by-group" id="toc-average-adjusted-predictions-by-group" class="nav-link" data-scroll-target="#average-adjusted-predictions-by-group">Average adjusted predictions by group</a></li>
  <li><a href="#comparisons" id="toc-comparisons" class="nav-link" data-scroll-target="#comparisons">Comparisons</a>
  <ul class="collapse">
  <li><a href="#observational-level-conditional" id="toc-observational-level-conditional" class="nav-link" data-scroll-target="#observational-level-conditional">Observational level (conditional)</a></li>
  <li><a href="#average-difference-marginal" id="toc-average-difference-marginal" class="nav-link" data-scroll-target="#average-difference-marginal">Average difference (marginal)</a></li>
  <li><a href="#more-specific-comparisons" id="toc-more-specific-comparisons" class="nav-link" data-scroll-target="#more-specific-comparisons">More specific comparisons</a></li>
  </ul></li>
  <li><a href="#counterfactuals-and-use-in-causal-analysis" id="toc-counterfactuals-and-use-in-causal-analysis" class="nav-link" data-scroll-target="#counterfactuals-and-use-in-causal-analysis">Counterfactuals and use in Causal analysis</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Marginal Effects</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>This example uses a cleaned version of the depression data from PAM6, and the <a href="https://vincentarelbundock.github.io/marginaleffects/index.html"><code>marginaleffects</code></a> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects); <span class="fu">library</span>(gtsummary)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse); <span class="fu">library</span>(ggpubr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>depress <span class="ot">&lt;-</span> <span class="fu">read.delim</span>(<span class="st">"C:/GitHub/AppliedStats_notes/data/depress_081217.txt"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(depress) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(depress))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>exa.dep <span class="ot">&lt;-</span> depress <span class="sc">%&gt;%</span> <span class="fu">select</span>(cases, age, income, sex, drink)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="making-predictions" class="level1">
<h1>Making Predictions</h1>
<p>In <a href="https://norcalbiostat.github.io/AppliedStatistics_notes/predicted-probabilities.html">ASCN 12.1</a> we looked at making predictions using the following logistic regression model for the likelihood of depression (except I’m adding the <code>drink</code> variable here).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dep_sex_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(cases <span class="sc">~</span> age <span class="sc">+</span> income <span class="sc">+</span> sex <span class="sc">+</span> drink, <span class="at">data=</span>exa.dep, <span class="at">family=</span><span class="st">"binomial"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(dep_sex_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age      income         sex       drink 
-0.92221015 -0.02010864 -0.03671841  0.94674920  0.25042232 </code></pre>
</div>
</div>
<p>There we mentioned that to calculate the predicted probability of being depressed for a specific covariate profile: e.g.&nbsp;a 44 year old woman making 20.6k annually.</p>
<p>This is also known as an “adjusted prediction”, “model-based”, or “regression-adjusted” prediction and is the fitted value <span class="math inline">\(\hat{p}_i\)</span> for a given combination of values <span class="math inline">\(X_i\)</span>.</p>
<p>We then saw how we could use the model to make predictions for all observations in the original dataset by using the <code>predict</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>dep.predict <span class="ot">&lt;-</span> <span class="fu">predict</span>(dep_sex_model, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dep.predict)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          2          3          4          5          6 
0.18396349 0.08402576 0.16002493 0.21225963 0.15792248 0.17389107 </code></pre>
</div>
</div>
<p>and then visualize the distribution of model predicted probabilities</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dep.predict)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="marginal_effects_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The <code>predictions()</code> function from the <code>marginaleffects</code> package can give us this information as well, but more readily provides the standard error with confidence interval for that single prediction, and binds it back onto the dataset used in the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>dep.pred.meff <span class="ot">&lt;-</span> <span class="fu">predictions</span>(dep_sex_model)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(dep.pred.meff) <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  rowid   estimate      p.value   conf.low conf.high cases age income sex drink
1     1 0.18396349 5.714805e-04 0.08807908 0.3447663     0  68      4   1     0
2     2 0.08402576 4.766854e-10 0.04145472 0.1628853     0  58     15   0     1
3     3 0.16002493 1.400929e-09 0.10022680 0.2457558     0  45     28   1     1
4     4 0.21225963 5.698388e-04 0.11331640 0.3622961     0  50      9   1     0
5     5 0.15792248 8.025076e-07 0.08798041 0.2671779     0  33     35   1     1
6     6 0.17389107 5.492250e-05 0.08984869 0.3097879     0  24     11   0     1</code></pre>
</div>
</div>
</section>
<section id="adjusted-predictions-at-the-mean" class="level1">
<h1>Adjusted predictions at the mean</h1>
<p>Sometimes we want to have a single estimate for the “average” prediction. First we look at the adjusted prediction for the ‘average’ person. This does not mean <span class="math inline">\(\bar{y}\)</span>, but the prediction when all predictors are held at their mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predictions</span>(dep_sex_model, <span class="at">newdata =</span> <span class="st">"mean"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Estimate Pr(&gt;|z|) 2.5 % 97.5 % age income   sex drink
    0.143   &lt;0.001 0.104  0.194  44     21 0.622 0.796

Columns: rowid, estimate, p.value, conf.low, conf.high, cases, age, income, sex, drink </code></pre>
</div>
</div>
<p>This output reports a predicted probability of depression of 0.144 (95% CI 0.104 - 0.194), for a 44 year old person making $21k a year. But what is sex=0.622 and drink= 0.79? These were categorical variables.</p>
<p>Because <code>sex</code> and <code>drink</code> were coded as 0/1, R treated them as numeric and thus is reporting a decimal value for the mean. However, this still makes sense because the mean of a boolean value is the proportion - so 62.2% of the individuals in this data were men, and 79.6% drank regularly. Remember, averages don’t have to be values actually observed on the data.</p>
</section>
<section id="average-adjusted-predictions-by-group" class="level1">
<h1>Average adjusted predictions by group</h1>
<p>What if my main research question is to better understand the effect of drinking on depression? Odds ratios are hard to understand, and sometimes it’s better to speak (or present results) in terms of predicted probabilities.</p>
<p>First, a plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>dep.pred.meff<span class="sc">$</span>reg_drinker <span class="ot">&lt;-</span> <span class="fu">factor</span>(dep.pred.meff<span class="sc">$</span>drink, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggdensity</span>(dep.pred.meff, </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">x =</span> <span class="st">"estimate"</span>, </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">add =</span> <span class="st">"mean"</span>, <span class="at">rug =</span> <span class="cn">TRUE</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>   <span class="at">color =</span> <span class="st">"reg_drinker"</span>, <span class="at">fill =</span> <span class="st">"reg_drinker"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>   <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="marginal_effects_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Great, so they’re different, but significantly different? Is <span class="math inline">\(p_{drink} \neq p_{no drink}\)</span>? We can use the <code>by</code> argument in <code>predictions()</code> to calculate the average adjusted prediction for different subsets of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predictions</span>(dep_sex_model, <span class="at">by =</span> <span class="st">"drink"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 drink Estimate Pr(&gt;|z|) 2.5 % 97.5 %
     0    0.133   &lt;0.001 0.069  0.243
     1    0.147   &lt;0.001 0.104  0.204

Columns: drink, estimate, p.value, conf.low, conf.high </code></pre>
</div>
</div>
<p>The predicted probability of depression for those that drink is 0.147 (95% CI 0.104 - 0.204), compared to the predicted probability of depression for someone that doesn’t drink 0.133 (95% CI 0.069, 0.243). Since these two intervals overlap, there’s not enough evidence to believe that they are significantly different. However, sometimes people need p-values to “enhance” conclusions such as that one (next section).</p>
</section>
<section id="comparisons" class="level1">
<h1>Comparisons</h1>
<section id="observational-level-conditional" class="level2">
<h2 class="anchored" data-anchor-id="observational-level-conditional">Observational level (conditional)</h2>
<p>The <code>comparisons</code> function creates predictions for each observation at different regressor values (e.g.&nbsp;male and female, drinking or no drinking), and then computes some measure of comparison such as a difference, ratio or odds.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>(dep.drink.comp <span class="ot">&lt;-</span> <span class="fu">comparisons</span>(dep_sex_model, <span class="at">variables =</span> <span class="st">"drink"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Term Contrast Estimate Std. Error     z Pr(&gt;|z|)    2.5 % 97.5 %
 drink    1 - 0  0.04059    0.06585 0.617    0.538 -0.08846 0.1696
 drink    1 - 0  0.01737    0.02759 0.630    0.529 -0.03671 0.0715
 drink    1 - 0  0.03087    0.04900 0.630    0.529 -0.06517 0.1269
 drink    1 - 0  0.04487    0.07205 0.623    0.533 -0.09635 0.1861
 drink    1 - 0  0.03053    0.04828 0.632    0.527 -0.06409 0.1251
--- 284 rows omitted. See ?avg_comparisons and ?print.marginaleffects --- 
 drink    1 - 0  0.01577    0.02480 0.636    0.525 -0.03284 0.0644
 drink    1 - 0  0.01147    0.01806 0.635    0.526 -0.02394 0.0469
 drink    1 - 0  0.00401    0.00672 0.597    0.550 -0.00915 0.0172
 drink    1 - 0  0.01493    0.02338 0.639    0.523 -0.03090 0.0608
 drink    1 - 0  0.04101    0.06599 0.621    0.534 -0.08833 0.1704
Columns: rowid, term, contrast, estimate, std.error, statistic, p.value, conf.low, conf.high, predicted, predicted_hi, predicted_lo, cases, age, income, sex, drink </code></pre>
</div>
</div>
<p>This output shows the observational level differences in predicted probability for each observation, under each value for the variable drink. Notice the contrast between regular drinking and non-drinking is different from row to row. This reflects that the impact of regular drinking has a different effect for different individuals.</p>
<p>We can plot these two predicted probabilities against each other (reference line in grey).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dep.drink.comp, <span class="fu">aes</span>(predicted_hi, predicted_lo)) <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">color =</span><span class="st">"grey"</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_fixed</span>() <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Reg Drinking"</span>, <span class="at">y =</span> <span class="st">"No Drinking"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="marginal_effects_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here we notice that the predicted probability of depression is higher for everyone if they were a regular drinker, and the difference in probabilities (potential impact of drinking on likelihood of depression) increases as the average predicted probability of depression increases.</p>
</section>
<section id="average-difference-marginal" class="level2">
<h2 class="anchored" data-anchor-id="average-difference-marginal">Average difference (marginal)</h2>
<p>By averaging these differences across all observations in our data set we get that regular drinking increases the average predicted probability of depression by 0.032 (-0.067, 0.13), a non-significant difference.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_comparisons</span>(dep_sex_model, <span class="at">variables =</span> <span class="st">"drink"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Term Contrast Estimate Std. Error     z Pr(&gt;|z|)   2.5 % 97.5 %
 drink    1 - 0   0.0315     0.0501 0.629    0.529 -0.0667   0.13

Columns: term, contrast, estimate, std.error, statistic, p.value, conf.low, conf.high </code></pre>
</div>
</div>
</section>
<section id="more-specific-comparisons" class="level2">
<h2 class="anchored" data-anchor-id="more-specific-comparisons">More specific comparisons</h2>
<p>What if we’re interested in something a bit more specific, such as</p>
<blockquote class="blockquote">
<p>Is the impact of regular drinking on depression greater for women than for men?</p>
</blockquote>
<p>or</p>
<blockquote class="blockquote">
<p>The effect of regular drinking for a 45 year old woman compared to a 45 year old man.</p>
</blockquote>
<p>We can specify a <code>datagrid</code> or grid of reference values (aka predictor space) to calculate this comparison on.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">comparisons</span>(dep_sex_model,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="st">"drink"</span>,  </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> <span class="fu">datagrid</span>(<span class="at">age =</span> <span class="dv">45</span>, <span class="at">sex =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Term Contrast Estimate Std. Error     z Pr(&gt;|z|)   2.5 % 97.5 % income age
 drink    1 - 0   0.0180     0.0282 0.638    0.524 -0.0373 0.0733     21  45
 drink    1 - 0   0.0367     0.0584 0.629    0.529 -0.0778 0.1513     21  45
 sex
   0
   1

Columns: rowid, term, contrast, estimate, std.error, statistic, p.value, conf.low, conf.high, predicted, predicted_hi, predicted_lo, cases, income, drink, age, sex </code></pre>
</div>
</div>
<ul>
<li>For a 45 year old male, regular drinking is associated with a 0.018 (-0.04, 0.07) increase in predicted probability of depression,</li>
<li>For a 45 year old female, regular drinking is associated with a 0.03 (-0.08, 0.15) increase in predicted probability of depression,</li>
</ul>
<p>Averaged across all subgroups and other variables;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_comparisons</span>(dep_sex_model,                          </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="st">"drink"</span>, </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> <span class="fu">datagrid</span>(<span class="at">age =</span> <span class="dv">45</span>, <span class="at">sex =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Term Contrast Estimate Std. Error     z Pr(&gt;|z|)   2.5 % 97.5 %
 drink    1 - 0   0.0274     0.0431 0.634    0.526 -0.0572  0.112

Columns: term, contrast, estimate, std.error, statistic, p.value, conf.low, conf.high </code></pre>
</div>
</div>
</section>
</section>
<section id="counterfactuals-and-use-in-causal-analysis" class="level1">
<h1>Counterfactuals and use in Causal analysis</h1>
<p>https://vincentarelbundock.github.io/marginaleffects/articles/gformula.html</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>